cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    eu1:
      email: eu@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: eu
      password: $2b$12$XlOjPDH45VOmI0TpiWitU.VSzbm1c09P1bo9TeuVIz2KW5qQFBeGO
    gabreru:
      email: gabreu@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: gabriel
      password: $2b$12$hcckRc/0bF6gYMmDz7c8fuam9JpmZhBdmDeHgxOUeGmiyXSIkRxM.
    leandro:
      email: leandro@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Leandro Brito lima
      password: $2b$12$NVag4GgPiyFnU43kYAqre.91pVBElUPX0iELCc8KNqKhUFqaZ7CCm
    limeru:
      email: lblima22@gmail.com
      failed_login_attempts: 3
      logged_in: false
      name: John Smith
      password: $2b$12$/3Tp.erxaSODR0uXUpZAwOa.cpCgXak3SlMlLowhug3ycyylC26o2
    lucas1:
      email: lucas@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: lucas
      password: $2b$12$s6jcIDUmdIxUdW9dkhisruQVZanRGubvGZNUpw7j7gN1IQuwXPnX6
    rebecca:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca
      password: $2b$12$sFTmNBzW5k6mqsdjTbUqm.u7ak6LyRJmRfVJuoDcnG5CfFuWJYQN6
pre-authorized:
  emails:
  - melsby@gmail.com
